version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: gradle
    directory: /android/app
    schedule:
      interval: weekly
    groups:
      android-app-gradle:
        patterns:
          - "*"
  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: weekly
    groups:
      android-gradle:
        patterns:
          - "*"
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
    groups:
      root-pub:
        patterns:
          - "*"
